name = "Adjustable Walking Speed - Rework"
prefix = "awsr"
author = "Miss Heda"
mainprefix = "z"

#modname = "{{prefix}}_mods"
#key_name = "{{prefix}}_{{version}}"
#authority = "{{prefix}}_{{version}}"

[files]
include = [
    "mod.cpp",
    "LICENSE.txt",
    "logo.paa",
]

[version]
git_hash = 0

#[properties]
#version = "{{git \"id 8\"}}"

[lint.sqf]
enabled = true # Default: true
exclude = [
    "a3/3DEN/UI/macroexecs.inc",
    "a3/ui_f/hpp/defineResincl.inc",
    "a3/ui_f/hpp/defineDIKCodes.inc",
    "a3/ui_f/hpp/defineCommonGrids.inc",
    "a3/ui_f/hpp/defineCommonColors.inc",
]



[asc]
enabled = true
exclude = [
    "/initsettings.sqf",
    "/initkeybinds.sqf",
    "/xeh_prep.sqf"
]

[hemtt.config]
preset = "Hemtt"

[hemtt.launch]
workshop = [
    "463939057", # ACE3's Workshop ID
    "1779063631", # Zeus Enhanced
    "450814997", # CBA_A3's Workshop ID
    "2369477168" # Advanced Dev Tools
]
parameters = [
    '"-profiles=C:\Users\Heda\OneDrive\Documents\Arma 3 - Other Profiles\Mia"'  
]
dlc = [
    
]